version: "3"

volumes:
  postgres_data:

services:
  postgres:
    image: postgres:12.4
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5439:5432"

